### PR TITLE
fix: Fix of Contexts and Cleanups of pages when using Router

### PR DESCRIPTION
**Pull request by Hookyns**

### CODE REVIEW

**Comment by spion** [comment]
I think this change will break `useRouter` when the outlet isn't nested within the router. But I see we already have such an example and it seems to work - is it because of `createRoot` that we preserve the router context too?

**Review by spion — APPROVED** [review]

**Comment by spion** [comment]
Ah, I think I get it.

Passing the owner to the nested route custom element means we inherit whatever context it had. `createRoot` uses that owner to create a new (owner) scope, inheriting from the passed owner. It requires manual cleanup, which is also taken care of.

Its interesting that the owner argument isn't officially documented :thinking:  https://docs.solidjs.com/reference/reactive-utilities/create-root

**Comment by Hookyns** [comment]
> I think this change will break `useRouter` when the outlet isn't nested within the router. But I see we already have such an example and it seems to work - is it because of `createRoot` that we preserve the router context too?

IonRoute captures the Owner which is the IonRoute context. Outlet renders the ComponentRef component which restores the IonRoute context so it's like inside Router. But that means I broke this:

```tsx
export function App() {
  return <IonApp>
    <IonRouter>
      <IonRoute />
    </IonRouter>
    
    <SomeContext.Provider value={xyz}>
      <IonRouterOutlet />
    </SomeContext.Provider>
  </IonApp>;
}
```

Well,.. I didn't break it because it never worked 😆, but it still won't work. And I think we cannot fix this. 😞 Maybe we can just mention this in documentation; I don't think it's a big deal.

---

> Its interesting that the owner argument isn't officially documented 🤔

Hmm 🤔, you are right. I didn't see the docs. Interesting. I hope it's a new not yet documented feature rather than deprecated. 🥲

**Comment by spion** [comment]
> I don't think it's a big deal.

I agree. We do have a working context passing mechanism now, which is good enough.

edit: Thank you!!!

**Pull request merged**
